services:
  front:
    image: hamdiz0/qr-front
    ports:
      - "3000:80"
    depends_on:
      - api


  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: qrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data" # save data-base data

  
  api:
    image: hamdiz0/qr-api
    environment:
      CORS_ORIGIN: "*" # allow all traffic to use this api
      POSTGRES_HOST: db
      POSTGRES_DB: qrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3001:80"

volumes:
  db-data: