---
# api-deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api-deployment
    app: qr-code-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-pod
      app: qr-code-app
  template:
    metadata:
      labels:
        name: api-pod
        app: qr-code-app
    spec:
      containers:
        - name : api
          image: hamdiz0/qr-api:latest 
          ports :
          - containerPort: 80

---
# api-service

apiVersion: v1
kind: Service
metadata:
  name: api-svc

spec:
  selector:
    name: api-pod
    app: qr-code-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80