# build image
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --odit=dev ; npm cache clean --force

COPY . .

RUN npm run build

# base image
FROM alpine

RUN apk add nodejs

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

# copy the built application from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js

ENV PORT=80    

EXPOSE 80

CMD ["node", "./node_modules/.bin/next", "start"]