---
# api-deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api-deployment
    app: qr-code-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-pod
      app: qr-code-app
  template:
    metadata:
      labels:
        name: api-pod
        app: qr-code-app
    spec:
      containers:
        - name : vote
          image: hamdiz0/qr-api:1.0.1
          ports :
          - containerPort: 80
          env:
            - name: POSTGRES_DB
              value: "qrdb"
            - name: CORS_ORIGIN
              value: "*"
            - name: POSTGRES_HOST
              value: "db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"



---
# api-service

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    name: api-pod
    app: qr-code-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001