FROM python:3.12-slim

RUN apt-get update && \
    apt-get autoremove --purge

WORKDIR /opt/api

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

ENTRYPOINT [ "uvicorn" ,"main:app" ,"--host" ,"0.0.0.0" ,"--port" ,"80" ]